all :
	javac main/Main.java
clean:
	del "cpu\CPU.class"
	del	"exception\AddressingModeException.class"
	del	"loader\Loader.class"
	del	"main\Main.class"
	del "main\Mnemonic.class"
	del "main\Option.class"
	del "memory\Memory.class"
demo :
	java main/Main sample_code/executable01 -p